### ISSUE TITLE
Adicione ao F-Droid

### ISSUE THREAD

**Issue by pizzamaker** [renancunha33/diolinux_webapp2#1]
Aqui tem mais detalhes de como fazê-lo: https://f-droid.org/contribute/

**Comment by ghost** [comment]
Looks buildable, but we need a explicit license, e.g. by adding a LICENSE or COPYING file or by mentioning the license in the a readme.

**Comment by renancunha33** [comment]
I solved the problem:

License GPLv3 has been added in Project.

**Comment by renancunha33** [comment]
I solved the problem:

License GPLv3 has been added in Project.

2015-09-29 9:40 GMT-03:00 Boris Kraut notifications@github.com:

**Comment by ghost** [comment]
Thanks. Which package id should be used? `com.fullscreen` or `com.example.webview`? Does the first relate somehow to fullscreen.com? If not, I wouldn't use it. The latter on is rather not unique. If you don't know, you could settle with one tied to your github account, which should be unique-ish enough.

**Comment by renancunha33** [comment]
package com.fullscreen;

2015-09-29 12:42 GMT-03:00 Boris Kraut notifications@github.com:

**Comment by ghost** [comment]
Okay, last thing: AndroidManifest says...

```
android:versionCode="1"
android:versionName="2.0"
```

but gradle specifies

```
        versionCode 1
        versionName "2.1.2.5"
```

I would stick with one place for such information. Also keep in mind to update the versionCode, if you release another version -- Android doesn't care about versionName, but just compares the integer if versionCode to check for updates.

Thanks for the quick response, finishing up the build. Should be ready for tonights build job.

Ref: https://gitlab.com/fdroid/fdroiddata/commit/6eec55dbf438ef2ad04315ad295dd4e4f8be1bf3

**Comment by renancunha33** [comment]
I forgot to update the manifest, sorry. But the version is the gradle one.

Thanks
Em 29/09/2015 12:54, "Boris Kraut" notifications@github.com escreveu:

**Comment by pizzamaker** [comment]
Done: https://f-droid.org/repository/browse/?fdid=com.fullscreen
